name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - dev
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main
      - dev

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    name: Run linters
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain
        run: |
          rustup toolchain install -c clippy -c rustfmt --profile minimal nightly
          rustup default nightly
      - uses: Swatinem/rust-cache@v2
        name: Setup Rust cache
        with:
          shared-key: ${{ matrix.os }}-ci
          save-if: ${{ github.ref == 'refs/heads/main' }}
      # Install your linters here
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run linters
        uses: wearerequired/lint-action@master
        with:
          rustfmt: true
          clippy: false
          auto_fix: true
          commit_message: "chore: apply linting fixes with ${linter}"
          git_name: "github-actions[bot]"
          git_email: "41898282+github-actions[bot]@users.noreply.github.com"
